import Header from "@/components/Header";
import "@/styles/global.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="homepage-body" style={{ backgroundColor: "#11001a", textDecoration: "underline" }}>
        <main id="homepage-main">
          
          {children}
        </main>
      </body>
    </html>
  )
}
